function EnvironmentA2()    
    % ENVIRONMENTA2 renders the environment for assessment2

    % surfaces
    % floor
    surf([-2,-2;2,2] ...
    ,[-2,2;-2,2] ...
    ,[0.01,0.01;0.01,0.01] ...
    ,'CData',imread('cobble.png') ...
    ,'FaceColor','texturemap');
    % wall
    surf([-2,-2;-2,-2] ...
    ,[-2,-2;2,2] ...
    ,[3,0.01;3,0.01] ...
    ,'CData',imread('bricks.jpg') ...
    ,'FaceColor','texturemap');

    % objects
    % barrier
    PlaceObject('ExtendableGate.ply', ...
    [ 0.1 -2 0; -1.4 -2 0; ...
    0.1 2 0; -1.4 2 0;]);
    % operator
    PlaceObject('Worker.ply', ...
    [ 1.9 1 0.01 ]);
end